### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by xal-0** [sjsch/small-programming-language#1]
Here's a list of things that need to be done on the interpreter:

- Statements
  - [x] Expression statements
  - [x] Assignment statements (right now they assign to a variable, but they need to be changed to assign to an lvalue)
  - [x] Returns statements
  - [x] While statements
  - [x] For statements
 - Expressions
   - [x] Variable references
   - [x] Functions
   - [x] Calls
   - [x] Arithmetic (addition is in, need to add the other operations)
   - [x] If/if else/else expressions
   - [x] String literals
   - [x] Arrays literals
   - [x] Dictionary literals
   - [ ] True/false/null
   - [ ] Array access
   - [x] Dictionary lookup
   - [x] Boolean not, negation
 - Types & Built-ins
   - [x] Numbers
   - [x] Bools
   - [x] Strings
   - [x] Arrays
   - [x] Dictionaries
   - [x] Print
